### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Qpan77** [hiromu/VoiceConversion#2]
hello, could you share how to run your code?

**Comment by hiromu** [comment]
These sources are designed to take .stf files obtained from a voice dataset using [STRAIGHT](http://www-ie.meijo-u.ac.jp/labs/rj001/spLibs/straight/linux_download.html), but actually, the GMM-based approach used here is a bit old.
Rather, I would recommend you to refer to recent DNN-based implementations, such as [gantts](https://github.com/r9y9/gantts).
